-- Seeding Rempah Data
INSERT INTO Rempah (nama, deskripsi, manfaat_ids, image_url) VALUES
    ('adas', 'Adas digunakan dalam berbagai masakan untuk memberikan rasa yang unik. Adas juga diketahui memiliki manfaat untuk pencernaan.', ARRAY[3, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/adas.jpg'),
    ('andaliman', 'Andaliman, juga dikenal sebagai merica batak, memiliki rasa pedas dan sering digunakan dalam masakan Sumatra. Bumbu ini juga memiliki sifat anti-inflamasi.', ARRAY[9, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/andaliman.jpg'),
    ('asam jawa', 'Asam Jawa digunakan sebagai bumbu dan bahan dasar dalam banyak masakan tradisional Indonesia, serta memiliki sifat antioksidan.', ARRAY[1, 3], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/asam-jawa.jpg'),
    ('bawang bombai', 'Bawang bombai sering digunakan dalam berbagai masakan untuk memberikan aroma dan rasa yang khas.', ARRAY[1, 4], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/bawang-bombai.jpg'),
    ('bawang merah', 'Bawang merah sering digunakan sebagai bumbu dasar dalam berbagai masakan Indonesia.', ARRAY[4, 9], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/bawang-merah.jpg'),
    ('bawang putih', 'Bawang putih digunakan untuk memberikan aroma khas pada masakan dan memiliki sifat antibakteri.', ARRAY[1, 2], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/bawang-putih.jpg'),
    ('biji ketumbar', 'Biji ketumbar digunakan sebagai bumbu dan memiliki aroma yang khas. Ketumbar juga dapat membantu melancarkan pencernaan.', ARRAY[3, 5], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/biji-ketumbar.jpeg'),
    ('bunga lawang', 'Bunga Lawang atau pekak digunakan untuk memberikan aroma harum dalam masakan dan memiliki sifat antibakteri.', ARRAY[1, 2], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/lawang.jpg'),
    ('cengkeh', 'Cengkeh digunakan sebagai bumbu dan memiliki aroma yang kuat dan khas. Cengkeh juga dikenal dapat meredakan sakit gigi dan nyeri sendi.', ARRAY[2, 9], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/cengkeh.jpeg'),
    ('daun jeruk', 'Daun jeruk sering digunakan untuk memberikan aroma segar pada masakan.', ARRAY[4, 9], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/daun-jeruk.jpg'),
    ('daun kemangi', 'Daun kemangi digunakan sebagai hiasan atau bumbu dalam masakan dan memiliki sifat antibakteri.', ARRAY[9, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/daun-kemangi.png'),
    ('daun ketumbar', 'Daun ketumbar sering digunakan sebagai hiasan atau bumbu masakan dan dapat membantu mengurangi inflamasi.', ARRAY[9, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/daun-ketumbar.jpg'),
    ('daun salam', 'Daun salam sering digunakan untuk memberikan aroma khas pada masakan, serta dapat membantu meningkatkan daya tahan tubuh.', ARRAY[1, 3], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/daun-salam.jpeg'),
    ('jahe', 'Jahe digunakan dalam berbagai masakan dan minuman untuk memberikan rasa pedas dan aroma khas. Jahe juga bermanfaat untuk meredakan batuk dan mengurangi peradangan.', ARRAY[7, 9, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/jahe.jpeg'),
    ('jinten', 'Jinten sering digunakan dalam masakan Timur Tengah dan India. Jinten juga diketahui dapat melancarkan pencernaan.', ARRAY[3, 4], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/jinten.jpg'),
    ('kapulaga', 'Kapulaga digunakan untuk memberikan rasa dan aroma khas pada masakan, serta dapat menurunkan tekanan darah.', ARRAY[1, 4], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/kapulaga.jpeg'),
    ('kayu manis', 'Kayu manis digunakan untuk memberikan rasa manis dan aroma dalam masakan. Kayu manis juga dapat membantu menurunkan kadar gula darah.', ARRAY[4, 5], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/kayu-manis.jpg'),
    ('kayu secang', 'Kayu secang digunakan untuk memberikan warna merah pada minuman tradisional dan memiliki sifat antioksidan.', ARRAY[1, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/secang.jpg'),
    ('kemiri', 'Kemiri digunakan sebagai bumbu dan bahan dasar dalam berbagai masakan Indonesia, serta dapat mengurangi peradangan.', ARRAY[9, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/kemiri.jpg'),
    ('kemukus', 'Kemukus memiliki rasa pedas dan digunakan dalam beberapa masakan tradisional. Kemukus juga dapat meningkatkan daya tahan tubuh.', ARRAY[1, 2], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/kemukus.jpg'),
    ('kencur', 'Kencur digunakan dalam masakan tradisional Indonesia untuk memberikan aroma khas dan dapat membantu mengatasi insomnia.', ARRAY[6, 9], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/kencur.jpg'),
    ('kluwek', 'Kluwek digunakan dalam masakan untuk memberikan warna hitam dan rasa yang khas. Kluwek juga memiliki sifat antimikroba.', ARRAY[1, 9], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/kluwek.jpg'),
    ('kunyit', 'Kunyit digunakan untuk memberikan warna kuning dan rasa khas pada masakan. Kunyit juga dapat menurunkan berat badan dan menjaga kesehatan jantung.', ARRAY[5, 10, 15], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/kunyit.jpg'),
    ('lada', 'Lada digunakan sebagai bumbu utama dalam berbagai masakan untuk memberikan rasa pedas. Lada juga diketahui dapat meningkatkan metabolisme.', ARRAY[5, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/lada.jpg'),
    ('lengkuas', 'Lengkuas digunakan dalam berbagai masakan Indonesia untuk memberikan aroma dan rasa yang khas, serta memiliki sifat anti-inflamasi.', ARRAY[9, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/lengkuas.jpg'),
    ('pala', 'Pala digunakan sebagai bumbu dan memiliki aroma yang kuat dan manis. Pala juga dapat mengurangi nyeri sendi.', ARRAY[2, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/pala.jpg'),
    ('saffron', 'Saffron adalah bumbu mahal yang digunakan untuk memberikan warna dan rasa pada masakan, serta dapat membantu mengurangi depresi.', ARRAY[8, 10], 'https://example.com/images/saffron.jpg'),
    ('serai', 'Serai digunakan untuk memberikan aroma segar pada masakan dan minuman, serta dapat meningkatkan daya tahan tubuh.', ARRAY[1, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/serai.jpg'),
    ('vanili', 'Vanili digunakan sebagai bumbu untuk memberikan aroma manis pada kue dan masakan, serta dapat mengurangi stres.', ARRAY[8, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/vanili.jpg'),
    ('wijen', 'Wijen digunakan sebagai hiasan atau bumbu dalam berbagai masakan dan memiliki kandungan nutrisi yang tinggi.', ARRAY[1, 10], 'https://storage.googleapis.com/rempahpedia-image-repository/rempah/wijen.jpg');

-- Data seeding for table Jamu
INSERT INTO Jamu (nama, manfaat_ids, rempah_ids, penyakit) VALUES
    ('Jamu Kunyit Asam', ARRAY[5, 10, 14], ARRAY[23, 1, 3], ARRAY['Jantung'::Penyakit, 'Haid'::Penyakit]),
    ('Jamu Beras Kencur', ARRAY[3, 6, 12], ARRAY[21, 5, 7], ARRAY['Gangguan Pencernaan'::Penyakit, 'Insomnia'::Penyakit]),
    ('Jamu Jahe', ARRAY[7, 9, 11], ARRAY[15, 9, 10], ARRAY['Batuk'::Penyakit, 'Radang Tenggorokan'::Penyakit]),
    ('Jamu Sambiloto', ARRAY[1, 8, 13], ARRAY[17, 6, 4], ARRAY['Imunitas'::Penyakit]),
    ('Jamu Temulawak', ARRAY[4, 2, 15], ARRAY[14, 20, 22], ARRAY['Kolesterol'::Penyakit, 'Nyeri Sendi'::Penyakit]),
    ('Jamu Sereh', ARRAY[1, 5, 9], ARRAY[28, 14, 21], ARRAY['Imunitas'::Penyakit, 'Hipertensi'::Penyakit]),
    ('Jamu Kunci Sirih', ARRAY[3, 10, 12], ARRAY[21, 17, 22], ARRAY['Gangguan Pencernaan'::Penyakit, 'Haid'::Penyakit]),
    ('Jamu Cabe Puyang', ARRAY[4, 8, 14], ARRAY[14, 18, 21], ARRAY['Kolesterol'::Penyakit, 'Anemia'::Penyakit]),
    ('Jamu Kunci Pepet', ARRAY[2, 3, 5], ARRAY[17, 22, 23], ARRAY['Nyeri Sendi'::Penyakit, 'Gangguan Pencernaan'::Penyakit]),
    ('Jamu Sinom', ARRAY[6, 11, 12], ARRAY[23, 14, 19], ARRAY['Insomnia'::Penyakit]),
    ('Jamu Pahitan', ARRAY[1, 9, 10], ARRAY[22, 16, 21], ARRAY['Imunitas'::Penyakit, 'Jantung'::Penyakit]),
    ('Jamu Brotowali', ARRAY[5, 8, 14], ARRAY[21, 24, 25], ARRAY['Anemia'::Penyakit]),
    ('Jamu Meniran', ARRAY[2, 6, 8], ARRAY[17, 22, 24], ARRAY['Nyeri Sendi'::Penyakit]),
    ('Jamu Kencur Asem', ARRAY[1, 7, 10], ARRAY[21, 23, 25], ARRAY['Imunitas'::Penyakit, 'Batuk'::Penyakit]),
    ('Jamu Daun Jinten', ARRAY[3, 5, 12], ARRAY[22, 23, 25], ARRAY['Gangguan Pencernaan'::Penyakit]),
    ('Jamu Kencur Daun Sirih', ARRAY[2, 4, 9], ARRAY[21, 23, 25], ARRAY['Nyeri Sendi'::Penyakit]),
    ('Jamu Daun Saga', ARRAY[1, 6, 13], ARRAY[22, 23, 24], ARRAY['Imunitas'::Penyakit]),
    ('Jamu Daun Sambiloto', ARRAY[1, 7, 15], ARRAY[16, 21, 25], ARRAY['Imunitas'::Penyakit]),
    ('Jamu Secang', ARRAY[3, 5, 9], ARRAY[19, 22, 23], ARRAY['Gangguan Pencernaan'::Penyakit]),
    ('Jamu Daun Pegagan', ARRAY[1, 6, 11], ARRAY[21, 24, 25], ARRAY['Imunitas'::Penyakit]),
    ('Jamu Daun Salam', ARRAY[2, 9, 12], ARRAY[23, 22, 21], ARRAY['Nyeri Sendi'::Penyakit]),
    ('Jamu Daun Pandan', ARRAY[2, 6, 12], ARRAY[21, 24, 25], ARRAY['Nyeri Sendi'::Penyakit, 'Insomnia'::Penyakit]);

-- Data seeding for table Manfaat
INSERT INTO Manfaat (nama) VALUES
('Meningkatkan Daya Tahan Tubuh'),
('Mengurangi Nyeri Sendi'),
('Melancarkan Pencernaan'),
('Menurunkan Kolesterol'),
('Menurunkan Berat Badan'),
('Mengatasi Insomnia'),
('Meredakan Batuk'),
('Mengurangi Stres'),
('Mengurangi Peradangan'),
('Menjaga Kesehatan Jantung'),
('Menjaga Kesehatan Kulit'),
('Meningkatkan Fungsi Otak'),
('Menyehatkan Rambut'),
('Mengatasi Anemia'),
('Mengontrol Gula Darah');

-- Data seeding for table Jamu_Manfaat (relationships)
INSERT INTO Jamu_Manfaat (jamu_id, manfaat_id) VALUES
(1, 5), (1, 10), (1, 14), 
(2, 3), (2, 6), (2, 12), 
(3, 7), (3, 9), (3, 11), 
(4, 8), (4, 1), (4, 13), 
(5, 4), (5, 2), (5, 15), 
(6, 1), (6, 5), (6, 9), 
(7, 3), (7, 10), (7, 12), 
(8, 4), (8, 8), (8, 14), 
(9, 2), (9, 3), (9, 5), 
(10, 6), (10, 11), (10, 12), 
(11, 1), (11, 9), (11, 10), 
(12, 5), (12, 8), (12, 14), 
(13, 2), (13, 6), (13, 8), 
(14, 1), (14, 7), (14, 10), 
(15, 3), (15, 5), (15, 12), 
(16, 2), (16, 4), (16, 9), 
(17, 1), (17, 6), (17, 13), 
(18, 1), (18, 7), (18, 15), 
(19, 3), (19, 5), (19, 9), 
(20, 1), (20, 6), (20, 11), 
(21, 2), (21, 9), (21, 12), 
(22, 3), (22, 4), (22, 10);

-- Data seeding for table Jamu_Rempah (relationships)
INSERT INTO Jamu_Rempah (jamu_id, rempah_id) VALUES
(1, 23), (1, 1), (1, 3),
(2, 21), (2, 5), (2, 7),
(3, 15), (3, 9), (3, 10),
(4, 17), (4, 6), (4, 4),
(5, 14), (5, 20), (5, 22),
(6, 28), (6, 14), (6, 21),
(7, 21), (7, 17), (7, 22),
(8, 14), (8, 18), (8, 21),
(9, 17), (9, 22), (9, 23),
(10, 23), (10, 14), (10, 19),
(11, 22), (11, 16), (11, 21),
(12, 21), (12, 24), (12, 25),
(13, 17), (13, 22), (13, 24),
(14, 21), (14, 23), (14, 25),
(15, 16), (15, 21), (15, 25),
(16, 22), (16, 23), (16, 24),
(17, 19), (17, 23), (17, 22),
(18, 16), (18, 21), (18, 25),
(19, 21), (19, 24), (19, 25),
(20, 23), (20, 22), (20, 21),
(21, 21), (21, 24), (21, 25),
(22, 23), (22, 22), (22, 21);

-- Data seeding for table Rempah_Manfaat (relationships)
INSERT INTO Rempah_Manfaat (rempah_id, manfaat_id) VALUES
(1, 3), (1, 10),
(2, 9), (2, 10),
(3, 1), (3, 3),
(4, 1), (4, 4),
(5, 4), (5, 9),
(6, 1), (6, 2),
(7, 2), (7, 9),
(8, 9), (8, 10),
(9, 1), (9, 3),
(10, 7), (10, 9), (10, 10),
(11, 4), (11, 9),
(12, 9), (12, 10),
(13, 9), (13, 10),
(14, 3), (14, 4),
(15, 3), (15, 5),
(16, 6), (16, 9),
(17, 1), (17, 9),
(18, 5), (18, 10), (18, 15),
(19, 5), (19, 10),
(20, 9), (20, 10),
(21, 2), (21, 10),
(22, 8), (22, 10),
(23, 1), (23, 10),
(24, 8), (24, 10),
(25, 1), (25, 10),
(26, 2), (26, 10),
(27, 8), (27, 10),
(28, 1), (28, 10),
(29, 8), (29, 10),
(30, 1), (30, 10);

-- Data seeding for Jamu_Penyakit (relationships)
INSERT INTO Jamu_Penyakit (jamu_id, penyakit) VALUES
(1, 'Jantung'), (1, 'Haid'),
(2, 'Gangguan Pencernaan'), (2, 'Insomnia'),
(3, 'Batuk'), (3, 'Radang Tenggorokan'),
(4, 'Imunitas'), 
(5, 'Kolesterol'), (5, 'Nyeri Sendi'),
(6, 'Imunitas'), (6, 'Hipertensi'),
(7, 'Gangguan Pencernaan'), (7, 'Haid'),
(8, 'Kolesterol'), (8, 'Anemia'),
(9, 'Nyeri Sendi'), (9, 'Gangguan Pencernaan'),
(10, 'Insomnia'),
(11, 'Imunitas'), (11, 'Jantung'),
(12, 'Anemia'),
(13, 'Nyeri Sendi'),
(14, 'Imunitas'), (14, 'Batuk'),
(15, 'Gangguan Pencernaan'), 
(16, 'Nyeri Sendi'),
(17, 'Imunitas'),
(18, 'Gangguan Pencernaan'),
(19, 'Imunitas'),
(20, 'Imunitas'), (20, 'Anemia'),
(21, 'Nyeri Sendi'), (21, 'Insomnia'),
(22, 'Imunitas'), (22, 'Batuk');